# Generated by Django 6.1 on 2026-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='موبایل')),
                ('user_type', models.CharField(choices=[('user', 'کاربر عادی'), ('admin', 'ادمین'), ('superadmin', 'سوپر ادمین')], default='user', max_length=20, verbose_name='نوع کاربر')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('blocked', 'مسدود')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='نام پدر')),
                ('first_name_en', models.CharField(blank=True, max_length=100, verbose_name='نام لاتین')),
                ('last_name_en', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی لاتین')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'برادر'), ('female', 'خواهر')], max_length=10, verbose_name='جنسیت')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=10, verbose_name='وضعیت تاهل')),
                ('nationality', models.CharField(default='ایران', max_length=50, verbose_name='تابعیت')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره منزل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('emergency_name', models.CharField(blank=True, max_length=100, verbose_name='نام نزدیکان')),
                ('emergency_phone', models.CharField(blank=True, max_length=11, verbose_name='شماره نزدیکان')),
                ('emergency_relation', models.CharField(blank=True, max_length=50, verbose_name='نسبت')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='نام دانشگاه')),
                ('education_level', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا')], max_length=20, verbose_name='مقطع تحصیلی')),
                ('student_status', models.CharField(blank=True, choices=[('student', 'دانشجو'), ('graduate', 'فارغ\u200cالتحصیل'), ('professor', 'استاد')], max_length=20, verbose_name='وضعیت دانشجویی')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='شماره گذرنامه')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا گذرنامه')),
                ('has_disease', models.BooleanField(default=False, verbose_name='سابقه بیماری زمینه\u200cای')),
                ('disease_description', models.TextField(blank=True, verbose_name='توضیح بیماری')),
                ('has_asthma', models.BooleanField(default=False, verbose_name='سابقه بیماری آسم/ریوی')),
                ('has_allergy', models.BooleanField(default=False, verbose_name='حساسیت دارویی/غذایی')),
                ('allergy_description', models.TextField(blank=True, verbose_name='توضیح حساسیت')),
                ('military_status', models.CharField(blank=True, choices=[('exempt', 'معاف'), ('done', 'کارت پایان خدمت'), ('student', 'معافیت تحصیلی'), ('other', 'سایر')], max_length=20, verbose_name='وضعیت نظام وظیفه')),
                ('guardian_national_code', models.CharField(blank=True, max_length=10, verbose_name='کد ملی سرپرست')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='عکس پرسنلی')),
                ('national_card_image', models.ImageField(blank=True, null=True, upload_to='national_cards/', verbose_name='تصویر کارت ملی')),
                ('student_card_image', models.ImageField(blank=True, null=True, upload_to='student_cards/', verbose_name='تصویر کارت دانشجویی')),
                ('commitment_form', models.FileField(blank=True, null=True, upload_to='commitments/', verbose_name='تعهدنامه/رضایت\u200cنامه')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='passports/', verbose_name='تصویر گذرنامه')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
