# Generated by Django 6.1 on 2026-08-08 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('announcement_type', models.CharField(choices=[('info', 'اطلاعیه'), ('warning', 'هشدار'), ('welcome', 'خوش\u200cآمد')], default='info', max_length=20, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(verbose_name='از تاریخ')),
                ('end_date', models.DateTimeField(verbose_name='تا تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('file', models.FileField(blank=True, null=True, upload_to='downloads/', verbose_name='فایل')),
                ('category', models.CharField(choices=[('madahi', 'کلیپ مداحی'), ('memory', 'خاطره'), ('munajat', 'مناجات'), ('mouludi', 'کلیپ مولودی'), ('other', 'دانلوشته')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دانلوشته',
                'verbose_name_plural': 'دانلوشته\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='تصویر')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('views_count', models.IntegerField(default=0, verbose_name='بازدید')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('category', models.CharField(choices=[('article', 'دلنوشته'), ('memory', 'خاطره'), ('munajat', 'مناجات'), ('madahi', 'کلیپ مداحی'), ('mouludi', 'کلیپ مولودی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر اصلی')),
                ('extra_image1', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر اضافی ۱')),
                ('extra_image2', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر اضافی ۲')),
                ('extra_image3', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر اضافی ۳')),
                ('aparat_link', models.CharField(blank=True, max_length=200, verbose_name='لینک آپارات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('views_count', models.IntegerField(default=0, verbose_name='بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'دلنوشته',
                'verbose_name_plural': 'دلنوشته\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gallery', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ['-created_at'],
            },
        ),
    ]
