# Generated by Django 6.1 on 2026-08-08 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon', models.CharField(max_length=10, verbose_name='آیکون')),
                ('required_trips', models.IntegerField(verbose_name='تعداد سفر لازم')),
            ],
            options={
                'verbose_name': 'بج',
                'verbose_name_plural': 'بج\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='سوال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(verbose_name='از تاریخ')),
                ('end_date', models.DateTimeField(verbose_name='تا تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': 'نظرسنجی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'دلنوشته'), ('gallery', 'گالری')], max_length=20, verbose_name='نوع محتوا')),
                ('content_id', models.IntegerField(verbose_name='شناسه محتوا')),
                ('text', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('approved', 'تایید شده'), ('rejected', 'رد شده')], default='approved', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactive.comment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoveWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280, verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='love_wall_posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دیوار عشق',
                'verbose_name_plural': 'دیوار عشق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PilgrimLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(verbose_name='طول جغرافیایی')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'موقعیت زائر',
                'verbose_name_plural': 'موقعیت زائرین',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='متن گزینه')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='interactive.poll', verbose_name='نظرسنجی')),
            ],
            options={
                'verbose_name': 'گزینه نظرسنجی',
                'verbose_name_plural': 'گزینه\u200cهای نظرسنجی',
            },
        ),
        migrations.CreateModel(
            name='TripTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline/', verbose_name='تصویر')),
                ('event_date', models.DateField(verbose_name='تاریخ رویداد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_posts', to='trips.trip', verbose_name='سفر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تایم\u200cلاین سفر',
                'verbose_name_plural': 'تایم\u200cلاین\u200cهای سفر',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='interactive.polloption', verbose_name='گزینه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رای',
                'verbose_name_plural': 'آرا',
                'unique_together': {('user', 'option')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'دلنوشته'), ('gallery', 'گالری'), ('lovewall', 'دیوار عشق')], max_length=20, verbose_name='نوع محتوا')),
                ('content_id', models.IntegerField(verbose_name='شناسه محتوا')),
                ('reaction_type', models.CharField(choices=[('heart', '❤️'), ('pray', '🤲'), ('cry', '😢'), ('rose', '🌹')], max_length=10, verbose_name='نوع ریکشن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ریکشن',
                'verbose_name_plural': 'ریکشن\u200cها',
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='interactive.badge', verbose_name='بج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بج کاربر',
                'verbose_name_plural': 'بج\u200cهای کاربران',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
