# Generated by Django 6.1 on 2026-08-08 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سفر')),
                ('trip_type', models.CharField(choices=[('arbaeen', 'اربعین'), ('fatemiyeh', 'فاطمیه'), ('mashhad', 'مشهد'), ('qom', 'قم'), ('other', 'سایر')], max_length=20, verbose_name='نوع سفر')),
                ('audience', models.CharField(choices=[('public', 'عمومی'), ('khadamin', 'خادمین'), ('students', 'دانشجویان'), ('other', 'سایر')], default='public', max_length=20, verbose_name='مخصوص')),
                ('start_date', models.DateField(verbose_name='از تاریخ')),
                ('end_date', models.DateField(verbose_name='تا تاریخ')),
                ('cost', models.BigIntegerField(default=0, verbose_name='هزینه ثبت\u200cنام')),
                ('refund_amount', models.BigIntegerField(default=0, verbose_name='مبلغ عودت وجه')),
                ('refund_description', models.TextField(blank=True, verbose_name='توضیحات عودت وجه')),
                ('conditions', models.TextField(blank=True, verbose_name='شرایط سفر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('registration_open', models.BooleanField(default=False, verbose_name='ثبت\u200cنام باز است')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سفر',
                'verbose_name_plural': 'سفرها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=20, unique=True, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('cancelled', 'انصراف زائر'), ('attended', 'شرکت کرد'), ('absent', 'شرکت نکرد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('total_cost', models.BigIntegerField(default=0, verbose_name='مبلغ کل سفر')),
                ('paid_from_wallet', models.BigIntegerField(default=0, verbose_name='پرداخت از کیف پول')),
                ('paid_directly', models.BigIntegerField(default=0, verbose_name='پرداخت مستقیم')),
                ('remaining_amount', models.BigIntegerField(default=0, verbose_name='مبلغ باقیمانده')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('partial', 'نیمه\u200cکامل'), ('paid', 'کامل')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'آنلاین'), ('cash', 'نقدی'), ('wallet', 'کیف پول')], max_length=20, verbose_name='نحوه پرداخت')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('refund_requested', models.BooleanField(default=False, verbose_name='درخواست عودت وجه')),
                ('refund_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت عودت وجه')),
                ('admin_note', models.TextField(blank=True, verbose_name='توضیحات ادمین')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='trips.trip', verbose_name='سفر')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('datetime', models.DateTimeField(verbose_name='تاریخ و زمان')),
                ('status', models.CharField(choices=[('active', 'در حال اجرا'), ('closed', 'بسته شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_periods', to='trips.trip', verbose_name='سفر')),
            ],
            options={
                'verbose_name': 'دوره حضور و غیاب',
                'verbose_name_plural': 'دوره\u200cهای حضور و غیاب',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='حاضر')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('method', models.CharField(choices=[('qr', 'QR Code'), ('manual', 'دستی')], default='manual', max_length=10, verbose_name='نحوه ثبت')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='trips.attendanceperiod', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رکورد حضور',
                'verbose_name_plural': 'رکوردهای حضور',
                'unique_together': {('period', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TravelCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_trips', to=settings.AUTH_USER_MODEL, verbose_name='همسفر')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='trips.registration', verbose_name='ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'همسفر',
                'verbose_name_plural': 'همسفران',
                'unique_together': {('registration', 'companion')},
            },
        ),
    ]
