# Generated by Django 6.1 on 2026-08-08 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contributions/', verbose_name='تصویر')),
                ('total_amount', models.BigIntegerField(verbose_name='کل مبلغ مورد نیاز')),
                ('share_count', models.IntegerField(verbose_name='تعداد سهم')),
                ('share_amount', models.BigIntegerField(verbose_name='مبلغ هر سهم')),
                ('start_date', models.DateField(verbose_name='از تاریخ')),
                ('end_date', models.DateField(verbose_name='تا تاریخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_public', models.BooleanField(default=True, verbose_name='نمایش عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مشارکت مالی',
                'verbose_name_plural': 'مشارکت\u200cهای مالی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HampaQafele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ واریزی')),
                ('payment_type', models.CharField(choices=[('online', 'اینترنتی'), ('cash', 'نقدی')], default='online', max_length=10, verbose_name='نوع واریز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات/سفارش خاص')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'همپای قافله',
                'verbose_name_plural': 'همپای قافله',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هزینه')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('expense_date', models.DateField(verbose_name='تاریخ واریز')),
                ('document', models.FileField(blank=True, null=True, upload_to='expense_docs/', verbose_name='سند')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL, verbose_name='هزینه\u200cکننده')),
                ('recorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip', verbose_name='سفر')),
            ],
            options={
                'verbose_name': 'ریزهزینه',
                'verbose_name_plural': 'ریزهزینه\u200cها',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ContributionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_payments', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت\u200cکننده')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.financialcontribution', verbose_name='مشارکت مالی')),
            ],
            options={
                'verbose_name': 'پرداخت مشارکت',
                'verbose_name_plural': 'پرداخت\u200cهای مشارکت',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, verbose_name='موجودی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'شارژ'), ('withdraw', 'برداشت'), ('trip_payment', 'پرداخت سفر'), ('refund', 'عودت وجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('pending', 'در انتظار')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='شماره پیگیری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
    ]
